# Generated by Django 3.0.3 on 2020-02-17 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_rooms', '0001_initial'),
        ('app_settings', '0014_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_booking_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='Номер брони у источника')),
                ('date_from', models.DateTimeField(verbose_name='Заезд')),
                ('date_to', models.DateTimeField(verbose_name='Выезд')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость проживания')),
                ('person', models.IntegerField(default=1, verbose_name='Основных мест')),
                ('person_additional', models.IntegerField(default=0, verbose_name='Доп. мест')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('client_comment', models.TextField(blank=True, null=True, verbose_name='Пожелания клиента')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления брони')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_settings.Channel', verbose_name='Источник брони')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_rooms.Room', verbose_name='Номер')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_settings.Status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Брони',
                'ordering': ['-date_from', '-date_to'],
            },
        ),
    ]
