# Generated by Django 3.0.4 on 2020-04-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_type',
            field=models.IntegerField(choices=[(1, 'за сутки'), (2, 'за месяц'), (3, 'за час'), (4, 'за всё время'), (5, 'за 30 дней')], default=1, verbose_name='Стоимость за'),
        ),
    ]
