version: '2'
services:
  django:
    build: ./
    command: gunicorn mandarhan.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/usr/src/app/static:z
      - ./media:/usr/src/app/media:z
    ports:
      - 8000:8000
    env_file:
      - ./.env
  caddy:
    image: lgatica/django-caddy:latest
    links:
      - django:django
    environment:
      - PORT=8000
    ports:
      - 80:80
    volumes:
      - ./static:/var/www/static:z
      - ./media:/var/www/media:z
      - ./logs:/var/log:z
