# Generated by Django 2.2.7 on 2019-11-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='payment name')),
                ('my_order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['my_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='service name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price')),
                ('price_type', models.IntegerField(choices=[(0, 'единоразово'), (1, 'в сутки'), (2, 'в сутки / за человека'), (3, 'за человека'), (4, 'скидка в %')], default=0, verbose_name='price type')),
                ('maximum', models.IntegerField(blank=True, null=True, verbose_name='maximum value')),
                ('allow_apply_only_full_room', models.BooleanField(default=False, verbose_name='allow apply only full room')),
                ('my_order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='order')),
                ('exclude_services', models.ManyToManyField(blank=True, to='app_settings.Service', verbose_name='exclude services')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['my_order', 'name'],
            },
        ),
    ]
