# Generated by Django 2.2.7 on 2019-11-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_default_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='room amenity')),
                ('code', models.SlugField(verbose_name='code')),
                ('my_order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['my_order', 'name'],
            },
        ),
    ]
