# Generated by Django 2.2.7 on 2019-11-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_default_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='code',
            field=models.SlugField(help_text='this code using in channel manager', verbose_name='code'),
        ),
    ]
