# Generated by Django 2.2.7 on 2019-11-25 06:04

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0005_auto_20191125_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='назваие статуса проживания', max_length=60, verbose_name='name')),
                ('color', colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='color')),
                ('my_order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'residence status',
                'verbose_name_plural': 'residence statuses',
                'ordering': ['my_order'],
            },
        ),
    ]
