# Generated by Django 2.2.7 on 2019-11-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0011_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('ota', models.PositiveSmallIntegerField(choices=[(0, 'свободный'), (1, 'Ostrovok.ru'), (2, 'Booking.com')], default=0, verbose_name='Канал продаж')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('contact_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='contact name')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='client discount')),
                ('commission', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='commission percent')),
                ('my_order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'источник бронирования',
                'verbose_name_plural': 'источники бронирования',
                'ordering': ['my_order'],
            },
        ),
    ]
