# Generated by Django 2.2.7 on 2019-11-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0013_default_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('code', models.CharField(max_length=128, verbose_name='code')),
                ('limit', models.PositiveIntegerField(default=0, help_text='0 - без ограничений.', verbose_name='Лимит использования')),
                ('date_from', models.DateField(blank=True, help_text='Если пусто - без ограничения.', null=True, verbose_name='Срок действия от')),
                ('date_to', models.DateField(blank=True, help_text='Если пусто - без ограничения, в указанную дату купон уже не действует.', null=True, verbose_name='Срок действия до')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='discount')),
                ('price_type', models.PositiveSmallIntegerField(choices=[(0, '%'), (1, 'руб.')], default=0, verbose_name='price type')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
            },
        ),
    ]
