# Generated by Django 3.0.3 on 2020-02-17 16:01

import app.rooms.uploaders
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_settings', '0014_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='category name')),
                ('main_places', models.PositiveIntegerField(default=1, verbose_name='main places')),
                ('additional_places', models.PositiveIntegerField(default=0, verbose_name='additional places')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price')),
                ('price_type', models.IntegerField(choices=[(1, 'per room'), (2, 'per person')], default=1, verbose_name='price_type')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price for additional place')),
                ('allow_external_booking', models.BooleanField(default=False, verbose_name='allow external booking')),
                ('widget_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='widget category name')),
                ('widget_description', models.TextField(blank=True, null=True, verbose_name='widget category description')),
                ('room_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='room size')),
                ('additional_services', models.ManyToManyField(blank=True, to='app_settings.Service', verbose_name='additional services')),
                ('amenities', models.ManyToManyField(blank=True, to='app_settings.Amenity', verbose_name='room amenities')),
                ('payments', models.ManyToManyField(blank=True, to='app_settings.Payment', verbose_name='allow payment options')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='room name')),
                ('main_places', models.PositiveIntegerField(default=1, verbose_name='main places')),
                ('additional_places', models.PositiveIntegerField(default=0, verbose_name='additional places')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price for additional place')),
                ('allow_book_sleep_place', models.BooleanField(default=False, verbose_name='allow booking sleep place')),
                ('sleep_place_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='sleep place price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('export_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='export room name')),
                ('export_description', models.TextField(blank=True, null=True, verbose_name='export room description')),
                ('room_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='room size')),
                ('allow_external_booking', models.BooleanField(default=True, verbose_name='allow external booking')),
                ('additional_services', models.ManyToManyField(blank=True, to='app_settings.Service', verbose_name='additional services')),
                ('amenities', models.ManyToManyField(blank=True, to='app_settings.Amenity', verbose_name='room amenities')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_rooms.Category', verbose_name='category')),
                ('room_payments', models.ManyToManyField(blank=True, to='app_settings.Payment', verbose_name='allow payment options')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=app.rooms.uploaders.room_uploader, verbose_name='photo')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rooms.Room', verbose_name='room')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=app.rooms.uploaders.category_uploader, verbose_name='category photo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_rooms.Category')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
